### ISSUE TITLE
Threads are checking if folder exists at the same time. Exception occured for thread 47

### ISSUE THREAD

**Issue by Meez25** [Meezouney/Scrapper-books_to_scrape#1]
Exception in thread Thread-47 (get_book_url_from_category):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yann/Development/project2_Scrapper/extract.py", line 90, in get_book_url_from_category
    get_csv_from_book_url(
  File "/home/yann/Development/project2_Scrapper/extract.py", line 214, in get_csv_from_book_url
    write_dict_to_csv(book, timestamp, name_of_category)
  File "/home/yann/Development/project2_Scrapper/extract.py", line 291, in write_dict_to_csv
    os.makedirs(path)
  File "<frozen os>", line 225, in makedirs
Sophie's World from the Philosophy category
FileExistsError: [Errno 17] File exists: 'csv_files/'

**Comment by Meez25** [comment]
Fixed by waiting 1s after the first thread is created. So the path are created by the first thread and there won't be any issue with the other threads
